[project]
name = "langchain-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentic-learning>=0.4.2",
    "langchain[openai]>=1.1.0",
]
